language: go
go:
    - 1.11.x
    - 1.12.x
    - 1.13.x
    - 1.14.x
    - master
before_install:
    - go get github.com/mattn/goveralls
script:
    - go test -race -v ./...
after_success:
    - $HOME/gopath/bin/goveralls -service=travis-ci -ignore=duo_go_demo/duo_go_demo.go
